### PR TITLE
Add number lookup sample

### PR DESCRIPTION
**Pull request by ericasp16**
## Purpose

Add samples for the number lookup preview

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code
see the README in the pull request

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Review by guoqing2023 — APPROVED** [review]

**Comment by henikaraa** [comment]
#signoff

**Comment by henikaraa** [comment]
#sign-off

**Comment by henikaraa** [comment]
#sign-off

**Review by henikaraa — APPROVED** [review]

**Review by vac0224 — APPROVED** [review]
LGTM

**Comment by vac0224** [comment]
#sign-off

**Comment by vac0224** [comment]
@minwoolee-msft can you help us merge this?

**Comment by ericasp16** [comment]
> @minwoolee-msft can you help us merge this?

there are also corresponding samples for the 3 other core languages:
https://github.com/Azure-Samples/communication-services-javascript-quickstarts/pull/224
https://github.com/Azure-Samples/communication-services-dotnet-quickstarts/pull/154
https://github.com/Azure-Samples/communication-services-python-quickstarts/pull/46

**Review by vac0224 — APPROVED** [review]
LGTM

**Comment by vac0224** [comment]
#sign-off

**Review by vac0224 — APPROVED** [review]
Approve

**Review by vac0224 — APPROVED** [review]
keep trying

**Review by vac0224 — APPROVED** [review]
LGTM

**Review by minwoolee-msft — APPROVED** [review]

**Pull request merged**
